name: Integration Tests

on:
  workflow_call:
    inputs:
      project_test_file_path:
        required: false
        type: string
    secrets:
        nuget_github_server_url:
          required: true
        nuget_github_server_username:
          required: true
        nuget_github_server_password:
          required: true

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Run Integration Tests
      id: test
      run: dotnet test ${{ inputs.project_test_file_path }} --results-directory ./TestResults --logger "trx;LogFileName=integration-tests-results.trx"

    - name: Upload Integration Tests Results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Integration Tests Results
        working-directory: ${{ github.workspace }}\TestResults
        path: '*.trx'
        reporter: dotnet-trx
        max-annotations: '50'
        token: ${{ secrets.GITHUB_TOKEN }}
