name: Integration Tests

on:
  workflow_call:
    inputs:
      project_test_file_path:
        required: false
        type: string
    secrets:
        nuget_github_server_url:
          required: true
        nuget_github_server_username:
          required: true
        nuget_github_server_password:
          required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.x'

    - name: Prepare NuGet sources
      run: |
        dotnet nuget add source --username ${{ secrets.nuget_github_server_username }} --password ${{ secrets.nuget_github_server_password }} --store-password-in-clear-text --name github ${{ secrets.nuget_github_server_url }}

    - name: Run Integration Tests
      id: test
      run: dotnet test ${{ inputs.project_test_file_path }} --results-directory ./TestResults --logger "trx;LogFileName=integration-tests-results.trx"

    - name: Upload Integration Tests Results
      uses: dorny/test-reporter@a6ddd83ac95ff4586f5d3aceeb314d9a1841db95 # v3.0.0
      if: success() || failure()
      with:
        name: Integration Tests Results
        working-directory: ${{ github.workspace }}/TestResults
        path: '*.trx'
        reporter: dotnet-trx
        max-annotations: '50'
        token: ${{ secrets.GITHUB_TOKEN }}
