name: System Tests

on:
  workflow_call:
    inputs:
      project_test_file_path:
        required: false
        type: string
    secrets:
        nuget_github_server_url:
          required: true
        nuget_github_server_username:
          required: true
        nuget_github_server_password:
          required: true
        jira_base_url:
          required: true
        jira_user_email:
          required: true
        jira_api_token:
          required: true

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout source
      uses: actions/checkout@v2.5.0
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.1.1
      with:
        dotnet-version: '7.0.x'
      
    #- name: Run System Tests
      #id: test
      #run: dotnet test ${{ inputs.project_test_file_path }} --filter Category="System.Tests" --results-directory ./TestResults --logger "trx;LogFileName=system-tests-results.trx"

    - name: Failing step
      id: test
      run: exit 1

    - name: Login to Jira
      uses: atlassian/gajira-login@master
      if: failure()
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create Jira issue on job failure
      uses: atlassian/gajira-create@master
      if: failure()
      with:
        project: NWL
        issuetype: "Bug"
        summary: "System Tests failed for ${{ github.repository }}"
        description: "${{ steps.test.outputs.issue }}\n\nCreated from GitHub Action"
        fields: '{"customfield_10031": "billable"}'

    - name: Upload System Tests Results
      uses: dorny/test-reporter@v1.6.0
      with:
        name: System Tests Results
        working-directory: ${{ github.workspace }}\TestResults
        path: '*.trx'
        reporter: dotnet-trx
        max-annotations: '50'
        token: ${{ secrets.GITHUB_TOKEN }}
