name: Templates zip

on:
  workflow_call:
    inputs:
      templates_name:
        required: true
        type: string
      octo_auto_release_dev:
        required: false
        type: boolean
        default: false
      octo_auto_release_prod:
        required: false
        type: boolean
        default: false
    secrets:
      nuget_github_server_url:
        required: true
      nuget_github_server_username:
        required: true
      nuget_github_server_password:
        required: true
      nuget_azure_server_url:
        required: true
      nuget_azure_server_username:
        required: true
      nuget_azure_server_password:
        required: true
      octopus_server_url:
        required: true
      octopus_server_apikey:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.11
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.11
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: '6.0.x'

    - name: Prepare NuGet sources
      run: |
        dotnet nuget add source --username ${{ secrets.nuget_github_server_username }} --password ${{ secrets.nuget_github_server_password }} --store-password-in-clear-text --name github ${{ secrets.nuget_github_server_url }}
        dotnet nuget add source --username ${{ secrets.nuget_azure_server_username }} --password ${{ secrets.nuget_azure_server_password }} --store-password-in-clear-text --name azure ${{ secrets.nuget_azure_server_url }}

    - name: Install validation tool
      run: |
        dotnet tool install NoEffect.Generator --prerelease --global

    - name: Validate templates
      run: |
        dotnet ask validate

    - name: Install Octopus CLI
      if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/release') || github.ref == 'refs/heads/develop'
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.8
      with:
        version: latest

    - name: Determine Octopus release branch
      if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/release') || github.ref == 'refs/heads/develop'
      id: octopus-channel
      run: |
          echo "::set-output name=autorelease::false"

          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            echo "::set-output name=channel::Production"
            echo "::set-output name=notes::https://github.com/$GITHUB_REPOSITORY/releases/tag/$GITHUB_REF_NAME"

            if [[ ${{ inputs.octo_auto_release_prod }} == true ]]; then
              echo "::set-output name=autorelease::true"
            fi
          else
            echo "::set-output name=channel::Development"
            echo "::set-output name=notes::https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"

            if [[ ${{ inputs.octo_auto_release_dev }} == true ]]; then
              echo "::set-output name=autorelease::true"
            fi
          fi

    - name: Archive Release
      if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/release') || github.ref == 'refs/heads/develop'
      uses: thedoctor0/zip-release@0.6.0
      with:
        type: 'zip'
        filename: '${{ inputs.templates_name }}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig GitVersion.yml'

    - name: Octopus Create release
      if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/release') || github.ref == 'refs/heads/develop'
      run: |
          octo pack --format="NuPkg" --id="${{ inputs.templates_name }}" --version="${{ env.GITVERSION_NUGETVERSIONV2 }}" --include="${{ inputs.templates_name }}.zip"
          octo push --server="${{ secrets.octopus_server_url }}" --apiKey "${{ secrets.octopus_server_apikey }}" --space="Spaces-1" --package "${{ inputs.templates_name }}.${{ env.GITVERSION_NUGETVERSIONV2 }}.nupkg"
          octo create-release --project "${{ inputs.templates_name }}" --version "${{ env.GITVERSION_NUGETVERSIONV2 }}" --packageVersion "${{ env.GITVERSION_NUGETVERSIONV2 }}" --channel "${{ steps.octopus-channel.outputs.channel }}" --releaseNotes "${{ steps.octopus-channel.outputs.notes }}" --server "${{ secrets.octopus_server_url }}" --apiKey "${{ secrets.octopus_server_apikey }}"

          if ${{ steps.octopus-channel.outputs.autorelease }}; then
            octo deploy-release --project "${{ inputs.templates_name }}" --version "${{ env.GITVERSION_NUGETVERSIONV2 }}" --deployTo "${{ steps.octopus-channel.outputs.channel }}" --server "${{ secrets.octopus_server_url }}" --apiKey "${{ secrets.octopus_server_apikey }}"
          fi
