name: UI Tests

on:
  workflow_call:
    inputs:
      project_test_file_path:
        required: false
        type: string
      project_test_category:
        required: false
        type: string
    secrets:
        nuget_github_server_url:
          required: true
        nuget_github_server_username:
          required: true
        nuget_github_server_password:
          required: true

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout source
      uses: actions/checkout@v2.5.0
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.1.1
      with:
        dotnet-version: '7.0.x'

    - name: Run UI Tests
      id: test
      run: dotnet test ${{ inputs.project_test_file_path }} --filter Category="${{ inputs.project_test_category }}" --results-directory ./TestResults --logger "trx;LogFileName=ui-tests-results.trx"
