name: UI Tests (legacy)

on:
  workflow_call:
    inputs:
      project_test_file_path:
        required: true
        type: string
      project_test_category:
        required: false
        type: string
    secrets:
        nuget_github_server_url:
          required: true
        nuget_github_server_username:
          required: true
        nuget_github_server_password:
          required: true

jobs:
  build:
    uses: nowastelogistics/procedures/.github/workflows/wman-ui-tests.yml@master
    with:
      project_test_file_path: ${{ inputs.project_test_file_path }}
      project_test_category: ${{ inputs.project_test_category }}
